export const userData = [
  {
    firstName: 'John',
    lastName: 'Doe',
    emailAddress: 'john@example.com',
    accessLevel: 'Standard User',
    phonenumber: '123-456-7890',
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    emailAddress: 'jane@example.com',
    accessLevel: 'Primary User',
    phonenumber: '987-654-3210',
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    emailAddress: 'alice@example.com',
    accessLevel: 'Standard User',
    phonenumber: '555-555-5555',
  },
  {
    firstName: 'Bob',
    lastName: 'Brown',
    emailAddress: 'bob@example.com',
    accessLevel: 'Standard User',
    phonenumber: '111-222-3333',
  },
  {
    firstName: 'Emily',
    lastName: 'Davis',
    emailAddress: 'emily@example.com',
    accessLevel: 'Standard User',
    phonenumber: '444-444-4444',
  },
  {
    firstName: 'Michael',
    lastName: 'Wilson',
    emailAddress: 'michael@example.com',
    accessLevel: 'Primary User',
    phonenumber: '666-666-6666',
  },
  {
    firstName: 'Olivia',
    lastName: 'Taylor',
    emailAddress: 'olivia@example.com',
    accessLevel: 'Standard User',
    phonenumber: '777-777-7777',
  },
  {
    firstName: 'David',
    lastName: 'Martinez',
    emailAddress: 'david@example.com',
    accessLevel: 'Primary User',
    phonenumber: '888-888-8888',
  },
  {
    firstName: 'Sophia',
    lastName: 'Anderson',
    emailAddress: 'sophia@example.com',
    accessLevel: 'Standard User',
    phonenumber: '999-999-9999',
  },
  {
    firstName: 'William',
    lastName: 'Thomas',
    emailAddress: 'william@example.com',
    accessLevel: 'Standard User',
    phonenumber: '123-123-1234',
  },
  {
    firstName: 'Isabella',
    lastName: 'White',
    emailAddress: 'isabella@example.com',
    accessLevel: 'Primary User',
    phonenumber: '456-456-4567',
  },
  {
    firstName: 'James',
    lastName: 'Jackson',
    emailAddress: 'james@example.com',
    accessLevel: 'Standard User',
    phonenumber: '789-789-7890',
  },
  {
    firstName: 'Charlotte',
    lastName: 'Harris',
    emailAddress: 'charlotte@example.com',
    accessLevel: 'Standard User',
    phonenumber: '321-321-4321',
  },
  {
    firstName: 'Daniel',
    lastName: 'Nelson',
    emailAddress: 'daniel@example.com',
    accessLevel: 'Standard User',
    phonenumber: '654-654-7654',
  },
  {
    firstName: 'Emma',
    lastName: 'Garcia',
    emailAddress: 'emma@example.com',
    accessLevel: 'Primary User',
    phonenumber: '987-987-0987',
  },
];
export const viewSystemData = [
  {
    outputVoltage: '125V',
    batteryVoltage: '11V',
    upsType: 'Line-interactive',
    temperature: '28°C',
    updateDate: '2024-02-12',
  },
  {
    outputVoltage: '115V',
    batteryVoltage: '10V',
    upsType: 'Standby',
    temperature: '27°C',
    updateDate: '2024-02-11',
  },
  {
    outputVoltage: '130V',
    batteryVoltage: '14V',
    upsType: 'Double-conversion',
    temperature: '26°C',
    updateDate: '2024-02-10',
  },
  {
    outputVoltage: '120V',
    batteryVoltage: '12V',
    upsType: 'Online',
    temperature: '25°C',
    updateDate: '2024-02-14',
  },
  {
    outputVoltage: '110V',
    batteryVoltage: '13V',
    upsType: 'Offline',
    temperature: '30°C',
    updateDate: '2024-02-13',
  },
];
export const DealerManagementData = [
  {
    companyName: 'ABC Inc.',
    companyPhoneNo: '123-456-7890',
    companyEmail: 'info@abcinc.com',
    status: 'Active',
  },
  {
    companyName: 'XYZ Corp.',
    companyPhoneNo: '987-654-3210',
    companyEmail: 'info@xyzcorp.com',
    status: 'Inactive',
  },
  {
    companyName: 'PQR Ltd.',
    companyPhoneNo: '555-555-5555',
    companyEmail: 'info@pqrltd.com',
    status: 'Active',
  },
  {
    companyName: 'LMN Enterprises',
    companyPhoneNo: '111-222-3333',
    companyEmail: 'info@lmnenterprises.com',
    status: 'Inactive',
  },
  {
    companyName: 'JKL Industries',
    companyPhoneNo: '444-555-6666',
    companyEmail: 'info@jklindustries.com',
    status: 'Active',
  },
  {
    companyName: 'GHI Solutions',
    companyPhoneNo: '777-888-9999',
    companyEmail: 'info@ghisolutions.com',
    status: 'Inactive',
  },
  {
    companyName: 'DEF Services',
    companyPhoneNo: '333-222-1111',
    companyEmail: 'info@defservices.com',
    status: 'Active',
  },
  {
    companyName: 'MNO Innovations',
    companyPhoneNo: '666-777-8888',
    companyEmail: 'info@mnoinnovations.com',
    status: 'Inactive',
  },
  {
    companyName: 'STU Technologies',
    companyPhoneNo: '999-888-7777',
    companyEmail: 'info@stutechnologies.com',
    status: 'Active',
  },
  {
    companyName: 'VWX Enterprises',
    companyPhoneNo: '555-444-3333',
    companyEmail: 'info@vwxenterprises.com',
    status: 'Inactive',
  },
];

export const deviceData = [
  {
    id: 1,
    facilityName: 'Gym',
    facilityCategory: 'Gym',
    trainer: true,
    opening: '10 am',
    closing: '10 pm',
    days: 7,
    address: 'XYZ',
    city: 'Pasadana',
    state: 'CA',
    country: 'US',
    bookingOptions: 'No',
    description: 'XYZ',
    price: '',
    period: '',
  },
  {
    id: 2,
    facilityName: 'Complex (Tennis)',
    facilityCategory: 'Complex',
    trainer: false,
    opening: '10 am',
    closing: '10 pm',
    days: 7,
    address: 'XYZ',
    city: 'Pasadana',
    state: 'CA',
    country: 'US',
    bookingOptions: 'Yes',
    description: 'XYZ',
    price: '$200',
    period: 'Per Month',
  },
];
